name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .     # where your application code is
        file: ./docker/Dockerfile.user  # the location of the docker file
        push: true
        tags: nishanthredde/zelle-user-app  # Replace with your Docker Hub username and repository

    - name: Verify Pushed Image
      run: docker pull nishanthredde/zelle-user-app  # Replace with your Docker Hub username and repository
